/*
 Do not edit, this is autogenerated
 MIT Kevin Walchko (c) 2023
*/
#pragma once

#include <cstdint>
#include <string>

static
std::string id2str(uint8_t id) {
  if (id == 1) return "MESSAGES/VEC";
  if (id == 2) return "MESSAGES/QUAT";
  if (id == 4) return "MESSAGES/IMU";
  if (id == 5) return "MESSAGES/CAL";
  return "UNKNOWN";
}