# name: Cpp
# on: [push]

# jobs:
#     build:
#         runs-on: ubuntu-latest
#         steps:
#             - uses: actions/checkout@master
#             - name: Test yivo
#               run: |
#                 mkdir -p build
#                 cd build
#                 cmake ..
#                 make
#                 ./gtests/all-gtest

name: CheckPackage
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          max-parallel: 5
          fail-fast: true
          matrix:
            python-version: ["3.8", "3.9", "3.10", "3.11"]
        steps:
            - uses: actions/checkout@main
            - name: Setup Python ${{ matrix.python-version }}
              uses: actions/setup-python@main
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install packages
              run: |
                echo "Installing dependencies"
                python3 -m venv .venv
                source .venv/bin/activate
                pip install -U pip setuptools wheel poetry pytest
                poetry install
                pytest tests/